version: 2
updates:
  - package-ecosystem: cargo
    directory: / # Location of Cargo.lock
    assignees:
      - muleyuck
    schedule:
      interval: weekly
      day: saturday
      timezone: Asia/Tokyo
